<a href='https://www.instagram.com/lanlearning/'> <img src='../pimages/logosmall.png' width="100" height="100"/></a>
___
<center>Copyright LanLearning 2020</center>

# Welcome back, let's review Pandas Part 4!

Today we will be reviewing **how to drop columns** (which is apart of the data cleaning process) and **how to group a table by certain features/attributes**.

#### Let's get started!

Start off by importing the pandas library below:

In [1]:
import pandas as pd

Save the ```vgsales.csv``` file we've provided you as a DataFrame in a variable called ```vgsales```. Display the table below:

In [2]:
vgsales = pd.read_csv("vgsales.csv")
vgsales # this will display the table

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Review Section: 

Start by getting a list of video games published by Nintendo and print how many video games are published by Nintendo.

In [3]:
nintendo = vgsales[vgsales['Publisher'] == 'Nintendo']
nintendo

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [5]:
print('There are ' + str(len(nintendo)) + ' video games published by Nintendo.')

There are 703 video games published by Nintendo.

Now print the percentage of video games sold that were published by Nintendo.

In [4]:
print(str(100*(len(nintendo)/len(vgsales))) + '% of video games sold were published by Nintendo.')

4.2354500542234% of video games sold were published by Nintendo.

Now print a list of all the names of the games published by Nintendo.

In [5]:
nintendo['Name'].values

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii',
       'Wii Sports Resort', 'Pokemon Red/Pokemon Blue', 'Tetris',
       'New Super Mario Bros.', 'Wii Play', 'New Super Mario Bros. Wii',
       'Duck Hunt', 'Nintendogs', 'Mario Kart DS',
       'Pokemon Gold/Pokemon Silver', 'Wii Fit', 'Wii Fit Plus',
       'Super Mario World',
       'Brain Age: Train Your Brain in Minutes a Day',
       'Pokemon Diamond/Pokemon Pearl', 'Super Mario Land',
       'Super Mario Bros. 3', 'Pokemon Ruby/Pokemon Sapphire',
       'Pokemon Black/Pokemon White',
       'Brain Age 2: More Training in Minutes a Day',
       'PokÃ©mon Yellow: Special Pikachu Edition', 'Pokemon X/Pokemon Y',
       'Super Smash Bros. Brawl', 'Animal Crossing: Wild World',
       'Mario Kart 7', 'Pokemon HeartGold/Pokemon SoulSilver',
       'Super Mario 64', 'Super Mario Galaxy',
       'Pokemon Omega Ruby/Pokemon Alpha Sapphire',
       'Super Mario Land 2: 6 Golden Coins', 'Super Mario 3D Land',
       'Super Mario All-Stars', 'Pokemon FireRed/Pokemon LeafGreen',
       'Super Mario 64', 'Mario Kart 64', 'New Super Mario Bros. 2',
       'Donkey Kong Country', 'Animal Crossing: New Leaf',
       'Mario Party DS', 'Super Mario Kart', 'Wii Party', 'Mario Party 8',
       'Pokemon Black 2/Pokemon White 2', 'GoldenEye 007',
       'PokÃ©mon Platinum Version', 'Super Mario Galaxy 2',
       'The Legend of Zelda: Ocarina of Time', 'Super Mario Bros. 2',
       'Super Smash Bros. for Wii U and 3DS',
       'The Legend of Zelda: Twilight Princess',
       'Super Smash Bros. Melee', 'Mario Kart 8',
       'Mario Kart: Double Dash!!', 'Big Brain Academy',
       'Donkey Kong Country Returns', 'The Legend of Zelda',
       'PokÃ©mon Emerald Version', 'PokÃ©mon Crystal Version',
       'Super Mario Sunshine',
       'Dragon Quest IX: Sentinels of the Starry Skies', 'Tetris',
       'Super Smash Bros.', 'Super Mario Advance',
       'Mario Kart: Super Circuit', 'Super Mario World',
       'Pokemon Stadium', 'Dr. Mario', 'Pokemon Pinball',
       'Donkey Kong 64', 'Professor Layton and the Curious Village',
       'Super Mario Bros. 3', 'New Super Mario Bros. U',
       'Super Mario Land 3: Wario Land',
       'The Legend of Zelda: Phantom Hourglass',
       "Donkey Kong Country 2: Diddy's Kong Quest", 'Tomodachi Life',
       "Kirby's Dream Land", 'Super Mario Bros.',
       'Super Smash Bros. for Wii U and 3DS', "Link's Crossbow Training",
       'Pokemon Mystery Dungeon: Explorers of Time/Explorers of Darkness',
       'Diddy Kong Racing', 'Dr. Mario', 'Animal Crossing: City Folk',
       'The Legend of Zelda: A Link to the Past',
       'The Legend of Zelda: The Wind Waker',
       "Luigi's Mansion: Dark Moon", 'Splatoon', 'Nintendo Land',
       'Zelda II: The Adventure of Link', 'Super Mario 3D World',
       'The Legend of Zelda: Ocarina of Time', 'Excitebike',
       "Super Mario World 2: Yoshi's Island",
       'The Legend of Zelda: Skyward Sword', 'Star Fox 64', 'Golf',
       'Professor Layton and the Diabolical Box', 'Donkey Kong Land',
       'Monster Hunter 4 Ultimate',
       'Flash Focus: Vision Training in Minutes a Day',
       "The Legend of Zelda: Link's Awakening",
       "Mario & Luigi: Bowser's Inside Story",
       'Big Brain Academy: Wii Degree', 'Nintendogs + cats',
       'Super Paper Mario', 'PokÃ©mon Trading Card Game',
       'Friend Collection', 'Banjo-Kazooie', 'Pokemon Snap',
       "Luigi's Mansion",
       "Donkey Kong Country 3: Dixie Kong's Double Trouble!", 'Kung Fu',
       'Clubhouse Games', 'F-1 Race',
       'The Legend of Zelda: Spirit Tracks',
       "The Legend of Zelda: Majora's Mask",
       'Professor Layton and the Unwound Future',
       'English Training: Have Fun Improving Your Skills!',
       'Mario Party 9', 'Wii Music', 'Yokai Watch 2 Ganso/Honke',
       'Baseball', 'Killer Instinct', 'Super Mario Maker',
       'Rhythm Heaven', 'Animal Crossing', 'Star Wars Episode I Racer',
       'Personal Trainer: Cooking',
       'The Legend of Zelda: A Link Between Worlds', 'Donkey Kong',
       "Mike Tyson's Punch-Out!!", 'Star Fox',
       'Animal Crossing: Happy Home Designer', 'Kirby Super Star Ultra',
       'Wave Race 64', 'WarioWare: Smooth Moves',
       "Super Mario World 2: Yoshi's Island", 'F-Zero', "Yoshi's Story",
       'Metroid Prime', "Yoshi's Island DS",
       'Professor Layton and the Last Specter', 'Monster Hunter Tri',
       'Mario Paint', 'PokÃ©mon Stadium 2', 'Metroid',
       'The Legend of Zelda: A Link to the Past', 'Mario Party',
       'Mario vs. Donkey Kong: Mini-Land Mayhem!',
       'Super Mario Bros.: The Lost Levels',
       'Star Wars: Shadows of the Empire', 'Mario Strikers Charged',
       'Style Savvy', 'Super Mario All-Stars: Limited Edition',
       'Art Academy', 'PokÃ©mon Colosseum', 'Perfect Dark',
       'Mario Party 2', 'Mario Party 4', 'Ice Hockey', 'Pro Wrestling',
       "Kirby's Dream Land 2", 'Donkey Kong Land II',
       "The Legend of Zelda: Majora's Mask 3D", 'Mario Tennis',
       'WarioWare Touched!', 'Pokemon Ranger: Shadows of Almia',
       'Mario Bros.', 'Paper Mario: Sticker Star',
       'Kirby: Nightmare in Dream Land', 'Wario Land 4',
       'Paper Mario: The Thousand-Year Door', 'Monster Hunter Tri',
       'New Super Luigi U', "The Legend of Zelda: Link's Awakening DX",
       'Wario Land 3', "Kirby's Pinball Land", 'Donkey Kong Country',
       'Pokemon Ranger', 'Mario & Luigi: Superstar Saga',
       'Star Wars: Rogue Squadron', 'Tennis', 'Volleyball',
       'Super Mario RPG: Legend of the Seven Stars', 'Mahjong',
       'R.C. Pro-Am', 'Tetris DS', "Kirby's Epic Yarn", 'Golf',
       'Mario Sports Mix', 'Mario Party 5',
       'Pokemon Mystery Dungeon: Red/Blue Rescue Team',
       'Mario & Luigi: Dream Team',
       'PokÃ©mon Mystery Dungeon: Blue Rescue Team', 'Donkey Kong Country',
       '1080Â°: TenEighty Snowboarding', 'Fire Emblem: Awakening',
       'Super Street Fighter II', 'Tennis', 'SimCity', 'Rad Racer',
       'Soccer', 'Kirby Squeak Squad', 'Alleyway', 'Tetris DX',
       'Mario Super Sluggers', 'The Legend of Zelda: Oracle of Ages',
       'Mario Party 3', 'Yokai Watch', 'Star Fox Adventures',
       'Donkey Kong Country Returns',
       'The Legend of Zelda: Oracle of Seasons',
       'Mario Party: Island Tour', 'Pinball', 'Hey You, Pikachu!',
       'Kirby: Triple Deluxe', 'Metroid Prime 3: Corruption',
       'Dragon Quest VI: Realms of Revelation',
       'Professor Layton and the Mask of Miracle',
       'The Legend of Zelda: The Wind Waker', 'Wii Party U',
       'Kirby 64: The Crystal Shards', 'Metroid II: Return of Samus',
       'Golden Sun', 'Kid Icarus', 'Yoshi', "Kirby's Adventure",
       "Cruis'n USA",
       'Kanshuu Nippon Joushikiryoku Kentei Kyoukai: Imasara Hito ni wa Kikenai Otona no Joushikiryoku Training DS',
       'Personal Trainer: Math', "Kirby's Return to Dreamland",
       "Yoshi's Cookie", 'Metroid Fusion', 'Mario Party 6',
       'Super Scope 6', 'Kirby & the Amazing Mirror', 'Pikmin',
       'Mario Hoops 3 on 3', 'Kirby Air Ride',
       'Pokemon Battle Revolution', 'Baseball', 'Super Mario Strikers',
       'The Legend of Zelda: Twilight Princess',
       'Pokemon Mystery Dungeon: Explorers of Sky', 'Mario Party 7',
       'Donkey Kong Classics', 'Pokemon Pinball: Ruby & Sapphire',
       'Mario Party 10', 'Fire Emblem Fates',
       'Mario Golf: Toadstool Tour',
       'Donkey Kong Country: Tropical Freeze', 'F1 Race', 'Ice Climber',
       'Final Fantasy: Crystal Chronicles', 'Banjo-Tooie',
       'New Play Control! Mario Power Tennis', 'Nintendo World Cup',
       'Wario Land II', 'Mario Golf', 'Mario Superstar Baseball',
       'LEGO City Undercover', '4 Nin uchi Mahjong', 'Kirby Super Star',
       'Classic NES Series: Super Mario Bros.',
       'The Legend of Zelda: The Minish Cap', 'Super Metroid',
       'Inazuma Eleven 2', 'Metroid: Other M', 'Paper Mario',
       'Bravely Default: Flying Fairy', 'Pocket Monsters Stadium',
       "Yoshi's New Island", 'Mario & Luigi: Partners in Time',
       'Donkey Kong Jungle Beat', 'Metroid Prime 2: Echoes',
       'Pokemon Ranger: Guardian Signs', 'Gyromite',
       "Yoshi's Woolly World", 'Mystery Case Files: MillionHeir',
       'Yakuman', 'Kid Icarus: Uprising',
       'Pokemon Mystery Dungeon: Gates to Infinity', "Hogan's Alley",
       'Hyrule Warriors', 'Pokemon XD: Gale of Darkness',
       'Diddy Kong Racing DS', 'Tetris 2 (All region sales)',
       "Kirby Tilt 'n' Tumble", 'Donkey Kong Country 2',
       'WarioWare, Inc.: Mega MicroGame$', 'Mario Power Tennis',
       'Game & Watch Gallery 2', 'Game & Watch Gallery 3',
       'Golden Sun: The Lost Age', 'Pikmin 2', 'SolarStriker',
       'Mario vs. Donkey Kong 2: March of the Minis',
       "PokÃ©Park Wii: Pikachu's Adventure",
       'Captain Toad: Treasure Tracker', 'Kobe Bryant in NBA Courtside',
       'Final Fantasy I & II: Dawn of Souls',
       'Pokemon Super Mystery Dungeon', 'Mario Tennis',
       'Wario Land: Shake It!', 'Mario vs. Donkey Kong',
       'Jet Force Gemini', 'Qix', 'Donkey Konga', 'Pokemon Rumble Blast',
       'Pilotwings', 'Super R.C. Pro-Am', 'Fantasy Life', 'Donkey Kong',
       'PokÃ©mon Mystery Dungeon: Red Rescue Team (US weekly sales)',
       'Pilotwings 64', "Yoshi's Cookie", 'Donkey Kong Jr.', 'Pikmin 3',
       'The Legend of Zelda: Tri Force Heroes', 'F-Zero X', 'Popeye',
       'Tales of Symphonia', 'Endless Ocean', 'LEGO City Undercover',
       'Star Fox: Assault', 'Super Princess Peach', 'Pokemon Conquest',
       'Naruto: Clash of Ninja 2', 'F-Zero: Maximum Velocity',
       'Kirby: Mass Attack', 'Donkey Kong Land III', 'Bayonetta 2',
       'Excitebike 64', 'NES Open Tournament Golf',
       'Game & Watch Gallery', 'Xenoblade Chronicles',
       'Mario Party Advance', 'Tetris 2', 'Fire Emblem',
       'PilotWings Resort', 'Wii Play: Motion', 'Star Fox 64 3D',
       'Mario Tennis Open', 'The Legend of Zelda: Twilight Princess HD',
       'Balloon Fight', 'Disney Magical World', 'Fossil Fighters',
       'Classic NES Series: The Legend of Zelda',
       'Fire Emblem: The Sacred Stones',
       'Pokemon Card GB2: Here Comes Team GR!', 'Wii Fit U',
       'Endless Ocean: Blue World', 'The Legendary Starfy',
       'Kirby: Planet Robobot', 'Golden Sun: Dark Dawn',
       'Xenoblade Chronicles X', 'Metroid: Zero Mission', 'Clu Clu Land',
       'Killer Instinct Gold',
       'The Legend of Zelda: Four Swords Adventures', 'EarthBound',
       'Mario & Sonic at the Sochi 2014 Olympic Winter Games',
       "Capcom's Soccer Shootout",
       'Major League Baseball Featuring Ken Griffey Jr',
       'Personal Trainer: Walking', 'PokePark 2: Wonders Beyond',
       'Professor Layton and the Azran Legacy', 'Metroid Prime Hunters',
       'Tetris Party Deluxe', 'Pokemon Dash', 'Donkey Kong Country 3',
       'Jump Ultimate Stars', 'Mario & Luigi: Paper Jam', 'Sword of Mana',
       'Classic NES Series: Donkey Kong', 'Yoshi', 'Kirby: Canvas Curse',
       'Practise English!', 'Just Dance Wii', 'Style Savvy: Trendsetters',
       'Monster Hunter Tri', 'Rhythm Heaven: The Best+', 'Blast Corps',
       'WarioWare, Inc.: Mega Party Game$', 'Advance Wars',
       'Classic NES Series: Zelda II: The Adventure of Link',
       'Fire Emblem: Monsh? no Nazo', 'Mario Pinball Land',
       'Nintendo Presents: New Style Boutique 2 - Fashion Forward',
       "Kirby's Dream Collection: Special Edition", 'The Last Story',
       'Fossil Fighters: Champions', '100 Classic Books',
       'Wario: Master of Disguise', 'New Play Control! Pikmin',
       'F-Zero GX', 'Yoshi Topsy-Turvy',
       'Advance Wars 2: Black Hole Rising', 'Fire Emblem: Shadow Dragon',
       "Cruis'n World", 'Donkey Kong Barrel Blast',
       'Metroid Prime: Trilogy', 'Advance Wars: Days of Ruin',
       "Mario's Picross", 'Ganbaru Watashi no Kakei Diary',
       'New Play Control! Donkey Kong Jungle Beat',
       'Final Fantasy IV Advance', 'Game & Watch Gallery 4',
       'New Play Control! Pikmin 2', 'Wave Race: Blue Storm',
       'WarioWare D.I.Y.', "Mickey's Speedway USA", 'Pokemon Trozei!',
       "Kirby's Dream Course", 'Fire Emblem: Seisen no Keifu',
       'Rooms: The Main Building', 'Tetris Party Deluxe',
       'The Mysterious Murasame Castle', 'Donkey Kong Jungle Climber',
       'Classic NES Series: Dr. Mario', 'Hotel Dusk: Room 215',
       'Xenoblade Chronicles', 'Hamtaro: Ham-Hams Unite!',
       'DS Bimoji Training', 'Jump Super Stars', 'Excite Truck',
       'Inazuma Eleven', 'Fire Emblem: Path of Radiance',
       'Star Fox Command', 'Inazuma Eleven GO',
       'Kirby and the Rainbow Curse', 'Picross 3D',
       "Wayne Gretzky's 3D Hockey", 'Mario Tennis: Power Tour',
       'Naruto Shippuden: Clash of Ninja Revolution 3',
       'Kenkou Ouen Recipe 1000: DS Kondate Zenshuu', 'Jam With the Band',
       'Fire Emblem: Radiant Dawn', 'Wrecking Crew', 'Picross DS',
       'Tactics Ogre: The Knight of Lodis', 'Fortune Street',
       'Mario & Wario', 'Pokemon Art Academy', 'Steel Diver',
       'Children of Mana', 'Mario Golf: World Tour', 'FlingSmash',
       'Bravely Second: End Layer', 'Densetsu no Stafi', 'Bomberman Hero',
       'Dance Dance Revolution: Mario Mix', 'Classic NES Series: Pac-Man',
       'Art Academy: Lessons for Everyone',
       'Mario & Sonic at the Rio 2016 Olympic Games', 'Mother 1+2',
       'Puzzle & Dragons Z + Super Mario Bros. Edition',
       'Samurai Warriors 3', 'Pokemon Puzzle League',
       'Mario Tennis Ultra Smash', 'Mario Golf: Advance Tour',
       'Densetsu no Stafi 2', 'Sin and Punishment: Star Successor',
       'Wario World', "Eternal Darkness: Sanity's Requiem",
       'Master of Illusion', 'Classic NES Series: Metroid',
       'Mischief Makers', 'Famicom Mini: Super Mario Bros. 2',
       'Dr. Mario 64', "Zack & Wiki: Quest for Barbaros' Treasure",
       'Animal Crossing: Amiibo Festival', 'Hyrule Warriors',
       'Ogre Battle 64: Person of Lordly Caliber', 'The Wonderful 101',
       'Mario no Super Picross', 'Story of Seasons',
       'Advance Wars: Dual Strike', 'Battalion Wars',
       'RR64: Ridge Racer 64', 'Mother 3', 'Wii Sports Club',
       'Fire Emblem: Fuuin no Tsurugi', 'Donkey Konga 2',
       'Mystery Case Files: The Malgrave Incident', 'Yoshi Touch & Go',
       'Custom Robo V2', 'Chibi-Robo! Plug into Adventure!',
       'Super Soccer', 'Wario Land II (GBC)', 'Elite Beat Agents',
       'Pokemon Channel', 'Custom Robo', 'Pac-Man World 2',
       'Trauma Center: Under the Knife', 'Hamtaro: Ham-Ham Heartbreak',
       "Kirby's Dream Land 3", 'Tetrisphere',
       'Trauma Center: Second Opinion', 'Picross 2', 'Battalion Wars 2',
       'Fossil Fighters: Frontier', 'Star Fox: Zero', 'Stunt Race FX',
       'Etrian Odyssey', 'Classic NES Series: Ice Climber',
       "Pandora's Tower", 'Planet Puzzle League',
       'Classic NES Series: Castlevania', 'Custom Robo',
       'Dr. Mario / Puzzle League', "Kirby's Block Ball", 'Mario Golf',
       'Doubutsu no Mori', 'KuruKuru Kururin', 'Gameboy Gallery',
       'Trauma Center: New Blood', 'NES Remix', 'Rhythm Tengoku',
       'Fossil Fighters (JP sales)', 'Glory of Heracles', 'Trace Memory',
       'Punch-Out!!', 'The New Tetris', "Ken Griffey Jr.'s Slugfest",
       'Just Dance Wii 2', 'Battle & Get! Pokemon Typing DS',
       'Tales of Phantasia', 'Final Fantasy VI Advance',
       "Mega Man: Dr. Wily's Revenge", 'Mega Man II', 'Sing Party',
       'Pokemon Box: Ruby & Sapphire',
       'Donkey Kong GB: Dinky Kong & Dixie Kong',
       'ExciteBots: Trick Racing',
       'Moero! Nekketsu Rhythm Damashii: Osu! Tatakae! Ouendan! 2',
       'Baten Kaitos: Eternal Wings and the Lost Ocean',
       'Command & Conquer',
       'Tohoku Daigaku Karei Igaku Kenkyuusho - Kawashima Ryuuta Kyouju Kanshuu - Mono Sugoku Nou o Kitaeru 5-Funkan no Oni Training',
       'Magical Vacation', "America's Test Kitchen: Let's Get Cooking",
       'Fire Emblem: Shin Monshou no Nazo Hikari to Kage no Eiyuu',
       'DS Bungaku Zenshuu', 'Inazuma Eleven Strikers',
       'Final Fantasy V Advance', 'Polarium',
       'Classic NES Series: Bomberman', 'Fire Emblem: Thracia 776',
       'Mario & Sonic at the Rio 2016 Olympic Games',
       'Metroid Prime Pinball', 'NBA Courtside 2 featuring Kobe Bryant',
       "Freshly-Picked: Tingle's Rosy Rupeeland", 'NBA Courtside 2002',
       'Classic NES Series: Excitebike', 'Classic NES Series: Xevious',
       'DK: King of Swing', 'Densetsu no Stafi 3', 'Chibi-Robo! Zip Lash',
       'Game & Wario', 'Nintendo Presents: Crossword Collection',
       'Girls Mode 3: Kirakira Code', 'Meteos',
       'Last Window: The Secret of Cape West',
       'Tetris 2 (weekly jp sales)', 'Naruto Shippuden: Ninja Council 4',
       'Super Swing Golf', 'Super R-Type', 'Tetris Attack',
       'Hamtaro: Ham-Ham Games', "Kirby's Star Stacker",
       'Shin Megami Tensei x Fire Emblem',
       "Disney's Magical Quest Starring Mickey and Minnie",
       'Spirit Camera: The Cursed Memoir', 'Yoshi Touch & Go (JP sales)',
       'Code Name: S.T.E.A.M.',
       'Are You Smarter Than a 5th Grader? Back to School',
       'Heroes of Ruin', 'Solatorobo: Red the Hunter',
       'Little Battlers eXperience: Baku Boost',
       'Trade & Battle: Card Hero', 'Tekken 3D: Prime Edition',
       'Ninja Gaiden 3', "Disney's Magical Mirror Starring Mickey Mouse",
       'Disney Magic World 2', 'Active Health with Carol Vorderman',
       'Sudoku Gridmaster (JP sales)', 'Daigasso! Band Brothers',
       'Face Training', 'Magical Starsign (US sales)', 'GameBoy Wars',
       'PokÃ©mon I Choose You / Squirtle Squad Game Boy Advance Video',
       'Daigasso! Band Brothers P', 'Sudoku Gridmaster',
       'PokÃ©mon Beach Blank-out Blastoise / Go West Young Meowth Game Boy Advance Video',
       'Custom Robo Arena', 'Densetsu no Stafi 4',
       'Street Fighter Alpha 2', 'Itoi Shigesato no Bass Tsuri No. 1',
       'Cubivore: Survival of the Fittest', 'True Swing Golf',
       'DS Rakubiki Jiten', 'Starcraft 64', 'F-Zero: GP Legend',
       'Culdcept', 'Tetris Attack', 'Geist',
       'Okaeri! Chibi-Robo! Happy Richie Oosouji', 'Doshin the Giant',
       'Mr. Driller: Drill Spirits', 'Magnetica',
       'Kororinpa: Marble Mania', 'Illusion of Gaia',
       'Sin and Punishment',
       'PokÃ©mon: For Ho-Oh the Bells Toll!: Game Boy Advance Video',
       'Eyeshield 21: Max Devil Power', 'ASH: Archaic Sealed Heat',
       'Pocket Soccer League: Calciobit',
       'Fatal Frame: Maiden of Black Water', 'Zangeki no Reginleiv',
       'Kousoku Card Battle: Card Hero', 'Odama', 'Soma Bringer',
       'Famicom Mini: Famicom Tantei Club - Kieta Koukeisha Zenkouhen',
       'Irozuki Tingle no Koi no Balloon Trip', 'Picross 3D 2',
       'Dynasty Warriors Advance',
       'Mega Man Battle Network 5: Double Team DS (JP sales)',
       'Fatal Frame 2: Wii Edition',
       "Mickey's Speedway USA (weekly JP sales)",
       'Project Hacker: Kakusei', "L'Aigle de Guerre",
       'Nihon Keizai Shinbunsha Kanshuu: Shiranai Mamade wa Son o Suru Mono ya Okane no Shikumi DS',
       'Famicom Mini: Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo Zenkouhen',
       'Famicom Mini: Mappy', 'Touch Mechanic', 'Terranigma',
       'Brain Age: Concentration Training', 'Pokemon Rumble World',
       'Disney Art Academy', 'Inazuma Eleven 3',
       'Kurikin: Nano Island Story',
       'Tabi no Yubisashi Kaiwachou DS: DS Series 4 America',
       'Just Dance Wii U',
       'Famicom Mini: Famicom Mukashi Banashi - Shin Oniga Shima Zenkouhen',
       'Famicom Mini: Mario Bros.', 'Zero: Tsukihami no Kamen',
       'Famicom Mini: SD Gundam World Gachapon Senshi - Scramble Wars',
       'Famicom Mini: Star Soldier', 'Minna no Joushiki Ryoku TV',
       'Disaster: Day of Crisis',
       'Famicom Mini: Hikari Shinwa: Palutena no Kagami',
       'Mega Man Battle Network 5: Double Team DS (US sales)',

Get all of the **game names** that were published by either **Activision** or **Kemco** AND were produced in 2005 or later.

In [6]:
vgsales[((vgsales['Publisher'] == 'Activision') | (vgsales['Publisher'] == 'Kemco')) & (vgsales['Year'] > 2004)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
29,30,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
31,32,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
33,34,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
35,36,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.30,0.07,1.12,13.73
...,...,...,...,...,...,...,...,...,...,...,...
16411,16414,Teenage Mutant Ninja Turtles (3DS),3DS,2013.0,Action,Activision,0.01,0.00,0.00,0.00,0.01
16444,16447,Madagascar: Escape 2 Africa,PC,2008.0,Action,Activision,0.01,0.00,0.00,0.00,0.01
16501,16504,"Transformers: War for Cybertron (XBox 360, PS3...",PC,2010.0,Shooter,Activision,0.01,0.00,0.00,0.00,0.01
16537,16540,Transformers: Fall of Cybertron,PC,2012.0,Action,Activision,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01

Which company has more games published after 2004: **Activision** or **Nintendo**? Show code to support your answer.

In [7]:
activision = vgsales[(vgsales['Publisher'] == 'Activision') & (vgsales['Year'] > 2004)]
print (len(activision))
nintendo = vgsales[(vgsales['Publisher'] == 'Nintendo') & (vgsales['Year'] > 2004)]
print(len(nintendo))

# Activision

743
374

#### Let's practice data cleaning: dropping unwanted elements!

Referring to the same data set of video game sales, ```vgsales.csv```, remove the **"Year"** column and make sure it saves!

In [8]:
vgsales=vgsales.drop(labels='Year', axis='columns') 
vgsales

,Rank,Name,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

What function do we use to check if there is a null value?

**`.isna()`**

Check to see if there are any null values in the ```vgsales.csv``` data set.

In [9]:
vgsales.isna()

,Rank,Name,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
16593,False,False,False,False,False,False,False,False,False,False
16594,False,False,False,False,False,False,False,False,False,False
16595,False,False,False,False,False,False,False,False,False,False
16596,False,False,False,False,False,False,False,False,False,False
16597,False,False,False,False,False,False,False,False,False,False

What function do we use to fix null values?

**`.fillna()`**

Even though this data set doesn't have any null values, let's fill each value just in case!

In [10]:
vgsales.fillna(0)

,Rank,Name,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

Again, even though this data set has no null values, cleanse the ```vgsales.csv``` file for any null **columns** and **rows**.

In [50]:
vgsales = vgsales.dropna(axis = 'rows')
vgsales
vgsales = vgsales.dropna(axis = 'columns')
vgsales

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.01

Now we will continue to review data cleaning, transitioning from **dropping** to **grouping**.

Group the dataset by **genre** below:

In [51]:
vgsales.groupby('Genre')

Display the game genres' **averages** and then their **sums** in each column.

In [58]:
vgsales.groupby('Genre').mean()

,Rank,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Genre,,,,,,
Action,7973.879071,0.264726,0.158323,0.048236,0.056508,0.528100
Adventure,11532.787714,0.082271,0.049868,0.040490,0.013072,0.185879
Fighting,7646.511792,0.263667,0.119481,0.103007,0.043255,0.529375
Misc,8561.847039,0.235906,0.124198,0.061967,0.043312,0.465762
Platform,6927.251693,0.504571,0.227573,0.147596,0.058228,0.938341
Puzzle,9627.381443,0.212680,0.087251,0.098471,0.021564,0.420876
Racing,7961.515612,0.287766,0.190865,0.045388,0.061865,0.586101
Role-Playing,8086.174731,0.219946,0.126384,0.236767,0.040060,0.623233
Shooter,7369.367939,0.444733,0.239137,0.029221,0.078389,0.791885
Simulation,8626.085352,0.211430,0.130773,0.073472,0.036355,0.452364
Sports,7425.026428,0.291283,0.160635,0.057702,0.057532,0.567319
Strategy,10071.897210,0.100881,0.066579,0.072628,0.016681,0.257151

In [57]:
vgsales.groupby('Genre').sum()

,Rank,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Genre,,,,,,
Action,26441383,877.83,525.00,159.95,187.38,1751.18
Adventure,14831165,105.80,64.13,52.07,16.81,239.04
Fighting,6484242,223.59,101.32,87.35,36.68,448.91
Misc,14889052,410.24,215.98,107.76,75.32,809.96
Platform,6137545,447.05,201.63,130.77,51.59,831.37
Puzzle,5603136,123.78,50.78,57.31,12.55,244.95
Racing,9943933,359.42,238.39,56.69,77.27,732.04
Role-Playing,12032228,327.28,188.06,352.31,59.61,927.37
Shooter,9653872,582.60,313.27,38.28,102.69,1037.37
Simulation,7478816,183.31,113.38,63.70,31.52,392.20
Sports,17419112,683.35,376.85,135.37,134.97,1330.93
Strategy,6858962,68.70,45.34,49.46,11.36,175.12

Display each video game genre's **minimum** "Other Sales" and its **maximum** "Global Sales".

In [63]:
genre = vgsales.groupby('Genre').agg({'Other_Sales': 'min', 'Global_Sales': 'max'})
genre

              Other_Sales  Global_Sales
Genre
Action                0.0         21.40
Adventure             0.0         11.18
Fighting              0.0         13.04
Misc                  0.0         29.02
Platform              0.0         40.24
Puzzle                0.0         30.26
Racing                0.0         35.82
Role-Playing          0.0         31.37
Shooter               0.0         28.31
Simulation            0.0         24.76
Sports                0.0         82.74
Strategy              0.0          5.45

Now let's compare these two genres: **Sports** and **Puzzle**. Write a few observations comparing and contrasting the mean data between the two of them. (Hint: use ```.loc``` to isolate each specific genre)

In [65]:
compare = vgsales.groupby('Genre').mean()
compare.loc[['Sports', 'Puzzle']]

               Rank  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre
Sports  7425.026428  0.291283  0.160635  0.057702     0.057532      0.567319
Puzzle  9627.381443  0.212680  0.087251  0.098471     0.021564      0.420876

The genre "Sports" seems to be a lot more popular than "Puzzle" because across the board, its sales are all higher. Also, "Sports" average rank is also a lot higher than "Puzzle".

# Congratulations, you've reached the end!

Good job with completing today's assignment! You're on your way to becoming an amazing data scientist :) Thanks for sticking with it and keeping up with the cirriculum. As always, feel free to email **lanlearningservice@gmail.com** with any questions/concerns! Alternatively, you can also use **Piazza**. :)

### About this notebook: 
Developed by:  
**Madeleine Larson** 

Edited by:  
**Jacqueline Mei**


#### Your feedback and learning are important to us. Please leave us feedback on our work! 

Feedback link: https://forms.gle/XbC6dxXbqnP9JihV6